apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: external-secrets-k54-components
  namespace: "argocd"
spec: 
  destination:
    name: k54
    namespace: external-secrets
  project: default
  source:
    path: registry/clusters/k54/cluster-secret-store
    repoURL: https://github.com/k2-muse/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
